/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package balugo;

import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 2ndyrGroupC
 */
public class Loading extends javax.swing.JFrame {

    private boolean choosen = false;
    private Database db = new Database();
    private ArrayList<ArrayList> buyer = new ArrayList();

    /**
     * Creates new form Loading
     */
    public Loading() {

        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setResizable(false);
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setEnabledAll(updatePanel, false);
        this.setEnabledAll(deptPanel, false);
        this.setEnabledAll(deletePanel, false);

    }

    public static void setEnabledAll(Container container, boolean enabled) {
        Component[] components = container.getComponents();
        if (components.length > 0) {
            for (Component component : components) {
                component.setEnabled(enabled);
                if (component instanceof Container) { // has to be a container to contain components
                    setEnabledAll((Container) component, enabled); // the recursive call
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        home = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        searchBox = new javax.swing.JTextField();
        dropdown = new javax.swing.JComboBox<>();
        updateRadio = new javax.swing.JRadioButton();
        deleteRadio = new javax.swing.JRadioButton();
        deptRadio = new javax.swing.JRadioButton();
        SearchButton = new javax.swing.JButton();
        addPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AddButon = new javax.swing.JButton();
        fnameAdd = new javax.swing.JTextField();
        deptAdd = new javax.swing.JTextField();
        lnameAdd = new javax.swing.JTextField();
        noAdd = new javax.swing.JTextField();
        updatePanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        fnameUpdate = new javax.swing.JTextField();
        lnameUpdate = new javax.swing.JTextField();
        noUpdate = new javax.swing.JTextField();
        deptUpdate = new javax.swing.JTextField();
        passUpdate = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablex = new javax.swing.JTable();
        deptPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        value = new javax.swing.JTextField();
        addRadio = new javax.swing.JRadioButton();
        subtractRadio = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        manageButton = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        passDept = new javax.swing.JPasswordField();
        deletePanel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        passDelete = new javax.swing.JPasswordField();
        delete = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 255));

        home.setBackground(new java.awt.Color(204, 229, 255));

        jPanel2.setBackground(new java.awt.Color(204, 229, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("SEARCH"));

        searchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBoxActionPerformed(evt);
            }
        });

        dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Name", "cell num"}));
        dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownActionPerformed(evt);
            }
        });

        updateRadio.setText("UPDATE");
        updateRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateRadioMouseClicked(evt);
            }
        });
        updateRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRadioActionPerformed(evt);
            }
        });

        deleteRadio.setText("DELETE");
        deleteRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteRadioMouseClicked(evt);
            }
        });
        deleteRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRadioActionPerformed(evt);
            }
        });

        deptRadio.setText("DEBT MANAGEMENT");
        deptRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deptRadioMouseClicked(evt);
            }
        });
        deptRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptRadioActionPerformed(evt);
            }
        });

        SearchButton.setBackground(new java.awt.Color(0, 102, 255));
        SearchButton.setForeground(new java.awt.Color(255, 255, 255));
        SearchButton.setText("Search");
        SearchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchButtonMouseClicked(evt);
            }
        });
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dropdown, 0, 237, Short.MAX_VALUE)
                    .addComponent(searchBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(deleteRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deptRadio)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(SearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteRadio)
                    .addComponent(updateRadio)
                    .addComponent(deptRadio))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        addPanel.setBackground(new java.awt.Color(204, 229, 255));
        addPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("ADD"));

        jLabel3.setText("FNAME");

        jLabel4.setText("LNAME");

        jLabel5.setText("CELL NO.");

        jLabel6.setText("DEBT");

        AddButon.setBackground(new java.awt.Color(0, 102, 204));
        AddButon.setForeground(new java.awt.Color(255, 255, 255));
        AddButon.setText("ADD");
        AddButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButonMouseClicked(evt);
            }
        });
        AddButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButonActionPerformed(evt);
            }
        });

        fnameAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameAddActionPerformed(evt);
            }
        });

        deptAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptAddActionPerformed(evt);
            }
        });

        lnameAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameAddActionPerformed(evt);
            }
        });

        noAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deptAdd))
                    .addComponent(AddButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fnameAdd))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noAdd))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lnameAdd)))
                .addContainerGap())
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fnameAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addComponent(lnameAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(noAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(deptAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(AddButon)
                .addContainerGap())
        );

        updatePanel.setBackground(new java.awt.Color(204, 229, 255));
        updatePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("UPDATE"));

        jLabel11.setText("FNAME");

        jLabel12.setText("LNAME");

        jLabel13.setText("CELL NO.");

        jLabel14.setText("DEBT");

        jLabel15.setText("PASSWORD");

        jLabel7.setText("Fields with changes will reflect on the information on screen");

        jLabel17.setText("Please verify if it is you.");

        updateButton.setBackground(new java.awt.Color(0, 102, 204));
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("UPDATE");
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateButtonMouseClicked(evt);
            }
        });
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        fnameUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameUpdateActionPerformed(evt);
            }
        });

        lnameUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameUpdateActionPerformed(evt);
            }
        });

        noUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noUpdateActionPerformed(evt);
            }
        });

        deptUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptUpdateActionPerformed(evt);
            }
        });

        passUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updatePanelLayout = new javax.swing.GroupLayout(updatePanel);
        updatePanel.setLayout(updatePanelLayout);
        updatePanelLayout.setHorizontalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(updateButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, updatePanelLayout.createSequentialGroup()
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updatePanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fnameUpdate))
                            .addGroup(updatePanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lnameUpdate))))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, updatePanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noUpdate))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, updatePanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(deptUpdate))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, updatePanelLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, updatePanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passUpdate)))
                .addContainerGap())
        );
        updatePanelLayout.setVerticalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(fnameUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(lnameUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(noUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deptUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15))
                    .addComponent(passUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablex.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tablex.setForeground(new java.awt.Color(0, 0, 153));
        tablex.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "name", "cell number", "debt"
            }
        ));
        tablex.setGridColor(new java.awt.Color(153, 0, 0));
        jScrollPane1.setViewportView(tablex);

        deptPanel.setBackground(new java.awt.Color(204, 229, 255));
        deptPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("DEPT MANAGEMENT"));

        jLabel19.setText("VALUE");

        value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueActionPerformed(evt);
            }
        });

        addRadio.setText("ADD");
        addRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addRadioMouseClicked(evt);
            }
        });
        addRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRadioActionPerformed(evt);
            }
        });

        subtractRadio.setText("SUBTRACT");
        subtractRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subtractRadioMouseClicked(evt);
            }
        });
        subtractRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractRadioActionPerformed(evt);
            }
        });

        jLabel21.setText("Please verify if it is you.");

        jLabel22.setText("PASSWORD");

        manageButton.setBackground(new java.awt.Color(0, 102, 204));
        manageButton.setForeground(new java.awt.Color(255, 255, 255));
        manageButton.setText("MANAGE");
        manageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageButtonMouseClicked(evt);
            }
        });
        manageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageButtonActionPerformed(evt);
            }
        });

        jLabel28.setText("Fields with changes will reflect on the information on screen");

        javax.swing.GroupLayout deptPanelLayout = new javax.swing.GroupLayout(deptPanel);
        deptPanel.setLayout(deptPanelLayout);
        deptPanelLayout.setHorizontalGroup(
            deptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deptPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deptPanelLayout.createSequentialGroup()
                        .addGroup(deptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(deptPanelLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(24, 24, 24))
                    .addGroup(deptPanelLayout.createSequentialGroup()
                        .addGroup(deptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(deptPanelLayout.createSequentialGroup()
                                .addComponent(addRadio)
                                .addGap(18, 18, 18)
                                .addComponent(subtractRadio))
                            .addGroup(deptPanelLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passDept, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel21)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        deptPanelLayout.setVerticalGroup(
            deptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deptPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(deptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(deptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRadio)
                    .addComponent(subtractRadio))
                .addGap(29, 29, 29)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(41, 41, 41)
                .addGroup(deptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageButton)
                .addGap(55, 55, 55))
        );

        deletePanel.setBackground(new java.awt.Color(204, 229, 255));
        deletePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("DELETE"));

        jLabel20.setText("Fields with changes will reflect on the information on screen");

        jLabel29.setText("Please verify if it is you.");

        jLabel30.setText("PASSWORD");

        passDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passDeleteActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(0, 10, 204));
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deletePanelLayout = new javax.swing.GroupLayout(deletePanel);
        deletePanel.setLayout(deletePanelLayout);
        deletePanelLayout.setHorizontalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deletePanelLayout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addGroup(deletePanelLayout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passDelete)
                        .addGap(14, 14, 14))
                    .addGroup(deletePanelLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        deletePanelLayout.setVerticalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(passDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delete)
                .addContainerGap())
        );

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deletePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 326, Short.MAX_VALUE))
                .addContainerGap())
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deletePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(updatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(homeLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deptPanel.getAccessibleContext().setAccessibleName("DEBT MANAGEMENT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageButtonActionPerformed

    private void manageButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageButtonMouseClicked

        int tempDept = 0;
        if (passDept.getText().equals("123")) {
            String val = value.getText();
            boolean isNum = true;
            if (val.equals("")) {
                JOptionPane.showMessageDialog(new JFrame(), "no amount inputed");
            } else {
                for (int counter = 0; counter < val.length(); counter++) {
                    if (!Character.isDigit(val.charAt(counter))) {
                        isNum = false;
                        break;
                    }
                }
                if (isNum) {
                    int input = JOptionPane.showConfirmDialog(null, "are you sure you want to manage debt?", null, JOptionPane.OK_CANCEL_OPTION);
                    if (input == 0) {
                        if (subtractRadio.isSelected() || addRadio.isSelected()) {
                            for (ArrayList item : buyer) {
                                tempDept = Integer.valueOf((String) item.get(4));
                                try {
                                    if (subtractRadio.isSelected()) {
                                        tempDept -= Integer.valueOf(value.getText());

                                    } else if (addRadio.isSelected()) {
                                        tempDept += Integer.valueOf(value.getText());

                                    }

                                    db.updateDept((String) item.get(0), String.valueOf(tempDept));

                                    this.setEnabledAll(deptPanel, false);
                                } catch (ClassNotFoundException ex) {
                                    Logger.getLogger(Loading.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                            JOptionPane.showMessageDialog(new JFrame(), "transaction complete");
                        } else {
                            JOptionPane.showMessageDialog(new JFrame(), "no operation done");
                        }

                    } else {
                        JOptionPane.showMessageDialog(new JFrame(), "user did not proceed transaction");
                    }
                } else {
                    JOptionPane.showMessageDialog(new JFrame(), "we don't accept letters in amount field");
                }

            }

        } else {
            JOptionPane.showMessageDialog(new JFrame(), "wrong password", "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        }
        for (Component control : deptPanel.getComponents()) {
            if (control instanceof JTextField) {
                JTextField ctrl = (JTextField) control;
                ctrl.setText("");
            }
        }
    }//GEN-LAST:event_manageButtonMouseClicked

    private void subtractRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtractRadioActionPerformed

    private void subtractRadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subtractRadioMouseClicked
        addRadio.setSelected(false);
    }//GEN-LAST:event_subtractRadioMouseClicked

    private void addRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addRadioActionPerformed

    private void addRadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addRadioMouseClicked
        // TODO add your handling code here:

        subtractRadio.setSelected(false);
    }//GEN-LAST:event_addRadioMouseClicked

    private void valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueActionPerformed

    private void deptUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptUpdateActionPerformed

    private void noUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noUpdateActionPerformed

    private void lnameUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameUpdateActionPerformed

    private void fnameUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameUpdateActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonActionPerformed

    private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseClicked
        // TODO add your handling code here:
        if (passUpdate.getText().equals("123")) {
            String fnUpdate = fnameUpdate.getText().trim();
            String lnUpdate = lnameUpdate.getText().trim();
            String nUpdate = noUpdate.getText().trim();
            String dUpdate = deptUpdate.getText().trim();
            String f = "";
            String l = "";
            String n = "";
            String d = "";
            boolean isNum = true;
            boolean isDebt = true;
            boolean isElev=true;
            if (fnUpdate.equals("") && lnUpdate.equals("") && nUpdate.equals("") && dUpdate.equals("")) {
                JOptionPane.showMessageDialog(new JFrame(), "not a single thing is updated");
            } else {
                if (!nUpdate.equals("")) {
                    for (int counter = 0; counter < nUpdate.length(); counter++) {
                        if (!Character.isDigit(nUpdate.charAt(counter))) {
                            isNum = false;
                            break;
                        }
                    }
                }

                if (isNum) {
                    if (!dUpdate.equals("")) {
                        for (int counter = 0; counter < dUpdate.length(); counter++) {
                            if (!Character.isDigit(dUpdate.charAt(counter))) {
                                isDebt = false;
                                break;
                            }
                        }

                    }
                    if (isDebt) {
                        if(!nUpdate.equals("")){
                            if (nUpdate.length() != 11) {
                                isElev=false;
                        }
                        }
                        if(isElev){
                            int input = JOptionPane.showConfirmDialog(null, "are you sure you want to update?", null, JOptionPane.OK_CANCEL_OPTION);
                        // 0=yes, 1=no, 2=cancel
                        if (input == 0) {
                            for (ArrayList item : buyer) {
                                if (fnUpdate.isEmpty()) {
                                    f = (String) item.get(1);
                                } else {
                                    f = fnUpdate;
                                }
                                if (lnUpdate.isEmpty()) {
                                    l = (String) item.get(2);
                                } else {
                                    l = lnUpdate;
                                }
                                if (nUpdate.isEmpty()) {
                                    n = (String) item.get(3);
                                } else {
                                    n = nUpdate;
                                }
                                if (dUpdate.isEmpty()) {
                                    d = (String) item.get(4);
                                } else {
                                    d = dUpdate;
                                }

                                try {
                                    System.out.println(d);
                                    db.updateAll((String) item.get(0), f, l, n, d);
                                    this.setEnabledAll(updatePanel, false);
                                } catch (ClassNotFoundException ex) {
                                    Logger.getLogger(Loading.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                            JOptionPane.showMessageDialog(new JFrame(), "updated successfully");

                        } else {
                            JOptionPane.showMessageDialog(new JFrame(), "user did not proceed on updating");
                        }
                        }else{
                            JOptionPane.showMessageDialog(new JFrame(), "contact info should be 11 digits");
                        }
                        

                    } else {
                        JOptionPane.showMessageDialog(new JFrame(), "we don't accept letters in debts");
                    }

                } else {
                    JOptionPane.showMessageDialog(new JFrame(), "we don't accept letters in contact number");
                }

            }

        } else {
            JOptionPane.showMessageDialog(new JFrame(), "wrong password", "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        }
        for (Component control : updatePanel.getComponents()) {
            if (control instanceof JTextField) {
                JTextField ctrl = (JTextField) control;
                ctrl.setText("");
            }
        }
    }//GEN-LAST:event_updateButtonMouseClicked

    private void noAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noAddActionPerformed

    private void lnameAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameAddActionPerformed

    private void deptAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptAddActionPerformed

    private void fnameAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameAddActionPerformed

    private void AddButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButonActionPerformed

        String fname = fnameAdd.getText();
        String lname = lnameAdd.getText();
        String cell = noAdd.getText();
        String dept = deptAdd.getText();
        boolean isNum = true;
        boolean isDept = true;
        if (!fname.isEmpty() || !lname.isEmpty()) {
            if (dept.isEmpty()) {
                dept = "0";
            }
            if (cell.equals("")) {
                JOptionPane.showMessageDialog(new JFrame(), "contact info is required");
            } else {
                for (int counter = 0; counter < cell.length(); counter++) {
                    if (!Character.isDigit(cell.charAt(counter))) {
                        isNum = false;
                        break;
                    }
                }
                if (isNum) {
                    if (cell.length() == 11) {
                        if (!dept.equals("")) {
                            for (int counter = 0; counter < dept.length(); counter++) {
                                if (!Character.isDigit(dept.charAt(counter))) {
                                    isDept = false;
                                    break;
                                }
                            }

                        }
                        if (isDept) {
                            int input = JOptionPane.showConfirmDialog(null, "are you sure you want to add?", null, JOptionPane.OK_CANCEL_OPTION);
                            // 0=yes, 1=no, 2=cancel
                            if (input == 0) {
                                try {
                                    db.addBuyer(fname, lname, cell, dept);
                                    JOptionPane.showMessageDialog(new JFrame(), "info added");
                                } catch (ClassNotFoundException ex) {
                                    Logger.getLogger(Loading.class.getName()).log(Level.SEVERE, null, ex);

                                }
                            } else {
                                JOptionPane.showMessageDialog(new JFrame(), "The user did not proceed in adding");
                            }
                        } else {
                            JOptionPane.showMessageDialog(new JFrame(), "debt does not  accept letter");
                        }

                    } else {
                        JOptionPane.showMessageDialog(new JFrame(), "contact info must have 11 digits", "Dialog",
                                JOptionPane.ERROR_MESSAGE);

                    }
                } else {
                    JOptionPane.showMessageDialog(new JFrame(), "letters in contact field is discouraged", "Dialog",
                            JOptionPane.ERROR_MESSAGE);
                }
            }

            for (Component control : addPanel.getComponents()) {
                if (control instanceof JTextField) {
                    JTextField ctrl = (JTextField) control;
                    ctrl.setText("");
                }
            }
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "you must fill up either the firstname or lastname", "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_AddButonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void SearchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchButtonMouseClicked
        // TODO add your handling code here:

        String value = dropdown.getSelectedItem().toString();
        String query = searchBox.getText().trim();
        if (deleteRadio.isSelected()) {
            this.setEnabledAll(deletePanel, true);
            this.setEnabledAll(updatePanel, false);
            this.setEnabledAll(deptPanel, false);
        }
        if (updateRadio.isSelected()) {
            this.setEnabledAll(updatePanel, true);
            this.setEnabledAll(deletePanel, false);
            this.setEnabledAll(deptPanel, false);
        }
        if (deptRadio.isSelected()) {
            this.setEnabledAll(deptPanel, true);
            this.setEnabledAll(deletePanel, false);
            this.setEnabledAll(updatePanel, false);
        }
        if (value.equals("All")) {
            try {
                buyer = db.getAll();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Loading.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        if (value.equals("Name")) {

            if (query.split(" ").length == 1) {
                try {
                    buyer = db.getAllByName(query);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Loading.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {
                    String[] temp = query.split(" ");
                    buyer = db.getAllByCompleteName(temp[0], temp[1]);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Loading.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        if (value.equals("cell num")) {
            try {
                buyer = db.getAllByNumber(query);

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Loading.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        int c = 1;
        for (int i = 0; i < tablex.getRowCount(); i++) {
            for (int j = 0; j < tablex.getColumnCount(); j++) {
                tablex.setValueAt("", i, j);
            }
        }
        for (ArrayList item : buyer) {
            tablex.setValueAt(item.get(1) + " " + item.get(2), c, 0);
            tablex.setValueAt(item.get(3), c, 1);
            tablex.setValueAt(item.get(4), c, 2);
            c++;
        }

    }//GEN-LAST:event_SearchButtonMouseClicked

    private void deptRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptRadioActionPerformed
        // TODO add your handling code here:
        updateRadio.setSelected(false);
        deleteRadio.setSelected(false);
    }//GEN-LAST:event_deptRadioActionPerformed

    private void deptRadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deptRadioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deptRadioMouseClicked

    private void deleteRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRadioActionPerformed
        // TODO add your handling code here:
        updateRadio.setSelected(false);
        deptRadio.setSelected(false);
    }//GEN-LAST:event_deleteRadioActionPerformed

    private void deleteRadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteRadioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteRadioMouseClicked

    private void updateRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRadioActionPerformed
        // TODO add your handling code here:
        deptRadio.setSelected(false);
        deleteRadio.setSelected(false);
    }//GEN-LAST:event_updateRadioActionPerformed

    private void updateRadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateRadioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_updateRadioMouseClicked

    private void dropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_dropdownActionPerformed

    private void searchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBoxActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
        if (passDelete.getText().equals("123")) {
            int input = JOptionPane.showConfirmDialog(null, "are you sure you want to delete?", null, JOptionPane.OK_CANCEL_OPTION);
            // 0=yes, 1=no, 2=cancel
            if (input == 0) {
                for (ArrayList item : buyer) {
                    try {
                        db.deleteAll((String) item.get(0));
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(Loading.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    this.setEnabledAll(deletePanel, false);
                }
                JOptionPane.showMessageDialog(new JFrame(), "delete complete");
                for (Component control : deletePanel.getComponents()) {
                    if (control instanceof JTextField) {
                        JTextField ctrl = (JTextField) control;
                        ctrl.setText("");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "user did not proceed");
            }

        } else {
            JOptionPane.showMessageDialog(new JFrame(), "incorrect password", "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_deleteMouseClicked

    private void passDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passDeleteActionPerformed

    private void passUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passUpdateActionPerformed

    private void AddButonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButonMouseClicked
        // TODO add your handling code here:
        for (Component control : addPanel.getComponents()) {
            if (control instanceof JTextField) {
                JTextField ctrl = (JTextField) control;
                ctrl.setText("");
            }
        }
    }//GEN-LAST:event_AddButonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loading().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButon;
    private javax.swing.JButton SearchButton;
    private javax.swing.JPanel addPanel;
    private javax.swing.JRadioButton addRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton delete;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JRadioButton deleteRadio;
    private javax.swing.JTextField deptAdd;
    private javax.swing.JPanel deptPanel;
    private javax.swing.JRadioButton deptRadio;
    private javax.swing.JTextField deptUpdate;
    private javax.swing.JComboBox<String> dropdown;
    private javax.swing.JTextField fnameAdd;
    private javax.swing.JTextField fnameUpdate;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lnameAdd;
    private javax.swing.JTextField lnameUpdate;
    private javax.swing.JButton manageButton;
    private javax.swing.JTextField noAdd;
    private javax.swing.JTextField noUpdate;
    private javax.swing.JPasswordField passDelete;
    private javax.swing.JPasswordField passDept;
    private javax.swing.JPasswordField passUpdate;
    private javax.swing.JTextField searchBox;
    private javax.swing.JRadioButton subtractRadio;
    private javax.swing.JTable tablex;
    private javax.swing.JButton updateButton;
    private javax.swing.JPanel updatePanel;
    private javax.swing.JRadioButton updateRadio;
    private javax.swing.JTextField value;
    // End of variables declaration//GEN-END:variables

}
